import Head from "next/head";
import Layout from "../component/Layout";

export default function Home() {
  return (
     <Layout>
       <div>
        <Head>
          <title>PizzaShop</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <h1>Pizza Shop by Jolayemi</h1>        
        </main>
      </div>
     </Layout>
  );
}

